[cursor]
style = "beam"
vi_mode_style = "block"

[window]
padding = { x = 12, y = 12 }
opacity = 1

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 16

[keyboard]
bindings = [
  { key = "Enter", mods = "Control | Shift", action = "CreateNewWindow" },
  { key = "Enter", mods = "Control | Alt", action = "SpawnNewInstance" }
]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[general]
import = [
  "~/.config/alacritty/carbonfox.toml"
]

[terminal]
shell = "/bin/zsh"
