[cursor]
style = "beam"

[window]
padding = { x = 6, y = 6 }
opacity = 0.80

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 16

[keyboard]
bindings = [
  { key = "Enter", mods = "Control | Shift", action = "CreateNewWindow" },
  { key = "Enter", mods = "Control | Alt", action = "SpawnNewInstance" }
]

[colors]
cursor = { text = "0x16181a", cursor = "0xffffff" }

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[general]
import = [
  "~/.config/alacritty/nord.toml"
]

[terminal]
shell = "/bin/zsh"
