import = [
  "~/.config/alacritty/cyberdream.toml"
]

shell = "/bin/zsh"


[cursor]
style = "block"

[window]
padding = { x = 6, y = 6 }
opacity = 0.85

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 12

[keyboard]
bindings = [
  { key = "Enter", mods = "Control | Shift", action = "CreateNewWindow" },
  { key = "Enter", mods = "Control | Alt", action = "SpawnNewInstance" }
]

[colors]
cursor = { text = "0x16181a", cursor = "0xffffff" }

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
